#!/bin/bash
########################
# PwnBox installation script
# author : 
# date : 310519 - v1
########################
# ---------------------------------------------
#
# VERIFY RUN AS ROOT
#
# ---------------------------------------------
echo "
██████╗ ██╗    ██╗███╗   ██╗██████╗  ██████╗ ██╗  ██╗
██╔══██╗██║    ██║████╗  ██║██╔══██╗██╔═══██╗╚██╗██╔╝
██████╔╝██║ █╗ ██║██╔██╗ ██║██████╔╝██║   ██║ ╚███╔╝
██╔═══╝ ██║███╗██║██║╚██╗██║██╔══██╗██║   ██║ ██╔██╗
██║     ╚███╔███╔╝██║ ╚████║██████╔╝╚██████╔╝██╔╝ ██╗
╚═╝      ╚══╝╚══╝ ╚═╝  ╚═══╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝
"
if [[ $EUID -ne 0 ]]; then
   echo "Work like a true hacker ! run the script as ROOT !"
   exit 1
fi
# ---------------------------------------------
#
# INSTALLING DEPENDENCIES
#
# ---------------------------------------------
# ---------------------------------------------
# Update and upgrade raspbian to last version
# ---------------------------------------------
echo "---------------------------------------------"
echo "updating the system"
echo "---------------------------------------------"
the_ppa="deb http://archive.raspbian.org/raspbian stretch main contrib non-free"
if ! grep -q "^deb .*$the_ppa" /etc/apt/sources.list; then
    echo "Ajout du dépôt dans sources.list"
    echo "deb http://archive.raspbian.org/raspbian stretch main contrib non-free" >> /etc/apt/sources.list
    wget https://archive.raspbian.org/raspbian.public.key -O - | apt-key add -
fi
apt update -y
echo "---------------------------------------------"
echo "upgrading the system"
echo "---------------------------------------------"
apt upgrade -y
# ---------------------------------------------
# check and install dependencies and prerequies
# ---------------------------------------------
exists()
{
  command -v "$1" >/dev/null 2>&1
}
echo "---------------------------------------------"
echo "installing prerequies"
echo "---------------------------------------------"
## Git ##
if exists git; then
  echo 'The program Git exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing Git..'
  apt-get install git -y
fi
## curl ##
if exists curl; then
  echo 'The program curl exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing curl ..'
  apt-get install curl -y
fi
if exists python; then
  echo 'The program python exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing python ..'
  apt-get install python -y
fi
if exists python3; then
  echo 'The program python3 exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing python3 ..'
  apt-get install python3 -y
fi
echo "---------------------------------------------"
echo "installing dependencies"
echo "---------------------------------------------"
## hostapd ##
if exists hostapd; then
  echo 'The program hostapd exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing hostapd ..'
  apt-get install hostapd -y
fi
## dnsmasq ##
if exists dnsmasq; then
  echo 'The program dnsmasq exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing dnsmasq ..'
  apt-get install dnsmasq -y
fi
## apache2 ##
if exists apache2; then
  echo 'The program apache2 exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing apache2 ..'
  apt-get install apache2 -y
fi
## php ##
if exists php; then
  echo 'The program php exists!'
else
  echo 'Your system does not have the program'
  echo '###Installing php ..'
  apt-get install php -y
fi
#pip install scapy
#pip install pcapy
#pip install pypcap
# ---------------------------------------------
#
# BACKUPING CONFIGURATIONS FILES
#
# ---------------------------------------------
# ---------------------------------------------
# BACKUP IN  /home/pi/backup/
# ---------------------------------------------
echo "---------------------------------------------"
echo "backup full configuration files"
echo "---------------------------------------------"
mkdir /home/pi/backup
cp /etc/network/interfaces /home/pi/backup/
cp /proc/sys/net/ipv4/ip_forward /home/pi/backup/
cp /etc/apache2/apache2.conf  /home/pi/backup/
cp /etc/dhcpcd.conf /home/pi/backup/
cp /etc/dnsmasq.conf /home/pi/backup/
iptables-save > /home/pi/backup/iptables.backup
# ---------------------------------------------
#
# CONFIGURE THE NETWORK
#
# ---------------------------------------------
echo "---------------------------------------------"
echo "bypass the dhcpcd.conf ..."
echo "---------------------------------------------"
echo "denyinterfaces wlan1" >> /etc/dhcpcd.conf
#########################################################
#########################################################
echo "---------------------------------------------"
echo " Now editing the ip configuration"
echo "---------------------------------------------"
echo "
auto wlan1
allow-hotplug wlan1
iface wlan1 inet static
    address 192.168.50.1
    netmask 255.255.255.0
    network 192.168.50.0
" > /etc/network/interfaces
# ---------------------------------------------
#
# CONFIGURE THE DNS
#
# ---------------------------------------------
#########################################################
#########################################################
echo "---------------------------------------------"
echo "Now configuring dnsmasq"
echo "---------------------------------------------"
echo "
interface=wlan1
listen-address=192.168.50.1
bind-interfaces
server=8.8.8.8
domain-needed
bogus-priv
dhcp-range=192.168.50.50,192.168.50.150,12h
listen-address=192.168.50.1
" >> /etc/dnsmasq.conf
# ---------------------------------------------
#
# CONFIGURE HOSTAPD
#
# ---------------------------------------------
#########################################################
#########################################################
echo "---------------------------------------------"
echo "Now creating the wifi.conf for hostapd"
echo "---------------------------------------------"
# generating the defaut configuration file for exemple
touch /home/pi/wifi.conf
echo "
interface=wlan1
driver=nl80211
ssid=WIFI_GRATUIT
hw_mode=g
channel=0
ieee80211d=1
country_code=FR
ieee80211n=1
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
" >> /home/pi/wifi.conf
echo "---------------------------------------------"
echo "configuring the NAT"
echo "---------------------------------------------"
sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
#########################################################
#########################################################
echo "---------------------------------------------"
echo "configuring IPTABLES"
echo "---------------------------------------------"
iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
iptables -A FORWARD -i wlan0 -o wlan1 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan1 -o wlan0 -j ACCEPT
sh -c "iptables-save > /etc/iptables.ipv4.nat"
echo "up iptables-restore < /etc/iptables.ipv4.nat" >> /etc/network/interfaces
#########################################################
#########################################################
echo "---------------------------------------------"
echo "creating RogueAP"
echo "---------------------------------------------"
#git clone https://github.com/DanMcInerney/net-creds MITM-HTTP
#cd MITM-HTTP/
#python net-creds.py -i eth0

# echo 0 > /proc/sys/net/ipv4/ip_forward
# iptables-restore < /home/pi/backup/iptables.backup
# cp /home/pi/backup/interfaces /etc/network/interfaces 
# cp /home/pi/backup/ip_forward /proc/sys/net/ipv4/ip_forward 
# cp /home/pi/backup/apache2.conf /etc/apache2/apache2.conf  
# cp /home/pi/backup/dhcpcd.conf /etc/dhcpcd.conf  
# cp /home/pi/backup/dnsmasq.conf /etc/dnsmasq.conf 
